### PR TITLE
accounts-cluster-bench: Fix clippy / CI

### PR DESCRIPTION
**Pull request by joncinque**
#### Problem

The clippy CI job is currently failing due to too many arguments in a function introduced in #3987:
https://buildkite.com/anza/agave/builds/15544#0193ace5-f9fa-475e-91a2-81dd45120c13

#### Summary of changes

Add the annotation to appease clippy.

### CODE REVIEW

**Comment by steveluscher** [comment]
Already have a pr up! #4023

**Comment by joncinque** [comment]
A beautiful, thanks!
