### PR TITLE
runtime-transaction: enable hash atomic and vote-interface bincode features for tests

### PR DESCRIPTION
**Pull request by Philippwolf**
#### Problem

`cargo check -p solana-runtime-transaction --lib --tests` fails when the package is built in isolation, with two distinct feature-gating errors:

```
error[E0599]: no function or associated item named `new_unique` found for struct `solana_hash::Hash` in the current scope
   --> runtime-transaction/src/runtime_transaction/sdk_transactions.rs:215:25
    |
215 |         let bank_hash = Hash::new_unique();
    |                               ^^^^^^^^^^ function or associated item not found in `solana_hash::Hash`

(... 5 more occurrences across sdk_transactions.rs and transaction_view.rs ...)

error[E0425]: cannot find function `vote` in module `vote::instruction`
   --> runtime-transaction/src/runtime_transaction/sdk_transactions.rs:222:34
    |
222 |             vote::instruction::vote(&vote_keypair.pubkey(), &auth_keypair.pubkey(), votes);
    |                                ^^^^ the item is gated behind the `bincode` feature
```

Two separate feature gates, both invisible to workspace CI:

- `Hash::new_unique` is gated behind `solana-hash`'s `atomic` feature.
- `vote::instruction::vote` is gated behind `solana-vote-interface`'s `bincode` feature.

Workspace-wide builds (`cargo test --workspace`, the buildkite CI) succeed because other crates in the build graph request both features and cargo unifies them. Anyone running `cargo test -p solana-runtime-transaction --lib` to iterate on this crate's tests in isolation hits both errors at once.

Same root cause for `atomic` as #12277 (rpc-client) and #11524 (bloom benches). The `bincode` gating on `solana-vote-interface` is an additional instance of the same package-scoped feature-unification pattern surfacing on the same crate, so both fixes are bundled here.

I bumped into this while doing a follow-up audit after #12277 to see how widespread the pattern was so @joncinque doesn't get annoyed by it again. `solana-runtime-transaction` was the only other crate in the workspace where the pattern actually fails in isolation rather than being masked by a transitive feature-unifying dep.

#### Summary of Changes

- Add `solana-hash` to `[dev-dependencies]` with `features = ["atomic"]`.
- Enable `bincode` on the existing `solana-vote-interface` dev-dependency entry.
- Production `[dependencies]` surface is left unchanged so consumers of the library are unaffected.

### CODE REVIEW

**Review by joncinque — APPROVED** [review]
Looks good to me, thanks!

**Review by yihau — APPROVED** [review]
thank you! this addresses part of the blocker for the new ci check: https://github.com/anza-xyz/agave/pull/12314

**Review by tao-stones — APPROVED** [review]
Looks good tho we're trying to replace all bincode with wincode. Looking at the test that uses vote, I think it probably can be rewrite to not depend on solana-vote-interface. I'll do that as refactor after this is merged.
