### ISSUE TITLE
v1.17: SDK build error with `nightly` compiler due to pinned `ahash` version

### ISSUE THREAD

**Issue by acheroncrypto** [anza-xyz/agave#1572]
### Problem

https://github.com/anza-xyz/agave/blob/4a70bc1e00c572857546d44f059b8b6406539587/Cargo.toml#L135

This pinned version of `ahash` doesn't build with the `nightly` compiler (https://github.com/tkaitchuck/aHash/issues/200):

```
error[E0635]: unknown feature `stdsimd`
  --> /home/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.5/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
```

However, it works with `1.18` crates because `ahash` version is not pinned:

https://github.com/anza-xyz/agave/blob/7696b27311660e6cbe68e8f4324bd72d242b0348/Cargo.toml#L140

### Proposed solution

Unpin `ahash` in the [v1.17](https://github.com/anza-xyz/agave/tree/v1.17) branch.

**Comment by steviez** [comment]
Closing this out since the issue was reported with v1.17 and we're running with v2.1 on Solana MNB at the moment
