### ISSUE TITLE
Deployment Regression on Agave 4.x: Incompatibility between Legacy SBF Binaries and strict reject_broken_elFs validation

### ISSUE THREAD

**Issue by MrSh4d0w18** [anza-xyz/agave#13297]
Description
Since the transition of public clusters (Devnet/Testnet/Mainnet) to the Agave 4.x runtime, we are unable to deploy Anchor programs. We have hit a "No Man's Land" where legacy SBF binaries are rejected by the new ELF parser, and newer SBPF binaries are rejected due to inactive feature gates.

Environment
Cluster: Devnet (4.1.0-beta.2) / Testnet (4.1.0-rc.0)

Binary Source: Anchor 0.30.1

Toolchains Tested: * platform-tools v1.41-v1.43 (Produces sbf-solana-solana targets)

platform-tools v1.48+ (Produces sbpf-solana-solana targets)

Failure Modes
We have isolated two independent failure paths that block all deployment attempts:

1. Legacy SBF Binaries (Platform-tools v1.41–v1.43)
Error: Error: Deploying program failed: RPC response error -32002: Transaction simulation failed: Error processing Instruction 1: invalid account data for instruction

Observation: These binaries were deployable on Agave 1.x clusters.

Hypothesis: These binaries are being rejected by the new config.reject_broken_elFs = true logic introduced in the Agave 4.x deploy.rs runtime.

2. Modern SBPF Binaries (Platform-tools v1.48+)
Error: Detected sbpf_version required by the executable which are not enabled

Observation: These binaries utilize modern SBPF metadata but cannot be deployed because Loader-v4 and SIMD-0161 feature gates are currently inactive on public clusters.

Reproduction Steps
Build a standard Anchor program using platform-tools v1.43.

Attempt solana program deploy <binary>.so --url https://api.devnet.solana.com.

Observe failure at the verification stage.

Attempt build with --arch v0 (v1.48+ tools) to generate SBPF metadata.

Observe failure due to inactive Loader-v4 feature gate.

Verification Data
Binary ELF Header (v1.43):

Plaintext
Class: ELF64
Machine: Linux BPF
OS/ABI: UNIX - System V
ABI Version: 0
Local Validation: These same binaries deploy successfully on a local solana-test-validator running Agave 2.3.0 (which appears to lack the strict reject_broken_elFs check or has it configured differently than the public 4.x clusters).

Desired Outcome
We require either:

Documentation on the expected ELF modifications to pass the new reject_broken_elFs parser for legacy-style binaries.

An accelerated activation timeline for Loader-v4 / SBPF feature gates on public clusters to allow modern toolchains to deploy.

**Comment by MrSh4d0w18** [comment]
Update: I have identified that SIMD-0500 is currently being activated on the cluster. This confirms that the environment is undergoing a breaking migration away from the binary formats I am currently forced to use. I will await the activation of these feature gates to ensure full compatibility with the new Agave 4.x runtime standards.

**Comment by Lichtso** [comment]
Yes, SIMD-0500 requires `--arch v3` (SBPFv3), but that is only active on testnet and will become active on devnet tomorrow.

**Comment by sebscholl** [comment]
Experiencing the same issue, with successful testnet deploys and issues on devnet. Will wait till tomorrow! Is there any mainnet timelines to be aware of?

**Comment by LucasSte** [comment]
> Legacy SBF Binaries (Platform-tools v1.41–v1.43)
Error: Error: Deploying program failed: RPC response error -32002: Transaction simulation failed: Error processing Instruction 1: invalid account data for instruction

In this case, the error is the same one as case 2, isn't it?

This is what I see:

```
Error: Deploying program failed: RPC response error -32002: Transaction simulation failed: Error processing Instruction 1: invalid account data for instruction; 7 log messages:
  Program 11111111111111111111111111111111 invoke [1]
  Program 11111111111111111111111111111111 success
  Program BPFLoaderUpgradeab1e11111111111111111111111 invoke [1]
  Program 11111111111111111111111111111111 invoke [2]
  Program 11111111111111111111111111111111 success
  Detected sbpf_version required by the executable which are not enabled
  Program BPFLoaderUpgradeab1e11111111111111111111111 failed: invalid account data for instruction
```

**Comment by LucasSte** [comment]
I have found the issue:

> Legacy SBF Binaries (Platform-tools v1.41–v1.43)
> Error: Error: Deploying program failed: RPC response error -32002: Transaction simulation failed: Error processing Instruction > 1: invalid account data for instruction
> Observation: These binaries were deployable on Agave 1.x clusters.

This is an issue with the cluster yes. Deployment of old programs have been disabled. You should now use `--arch v3` with a recent platform tools version. Note that `--arch v3` will still fail with an old version.

> Modern SBPF Binaries (Platform-tools v1.48+)
> Error: Detected sbpf_version required by the executable which are not enabled

When you see that error without the extra logs, it means that your local Solana CLI is outdated. Since the command `solana program deploy` verifies your program locally before submitting a transaction, you'll see an error with `--arch v3` because v3 was not allowed in old versions.

I successfully deployed a program compiled with `cargo-build-sbf --arch v3` (platform tools version v1.54) to devnet using the most up-to-date Solana CLI tool.

**Comment by LucasSte** [comment]
> Yes, SIMD-0500 requires `--arch v3` (SBPFv3), but that is only active on testnet and will become active on devnet tomorrow.

It is already active on devnet:

```
$ solana feature status B8JJXCy5amZyWG9r7EnUYLwzXSXTxG7GZ1qZ1qggo83g --url devnet
Feature                                      | Status                  | Activation Slot | Description
B8JJXCy5amZyWG9r7EnUYLwzXSXTxG7GZ1qZ1qggo83g | active since epoch 1088 | 470016000       | SIMD-0500: Disable deployment of SBPF v0, v1 and v2 programs
```

**Comment by jalaziz** [comment]
Why does `cargo-build-sbf` default to `v0` if it's no longer accepted? The whole Solana development stack defaults to v0 (agave, anchor, etc) and there doesn't seem to be any guidance or announcements related to this breaking change in the changelogs.

I would expect using the latest version of the Solana development tools to work out of the box on devnet.

**Comment by Lichtso** [comment]
See discussion on Discord: https://discord.com/channels/428295358100013066/967028962746327060/1517048830145724486

> Why does cargo-build-sbf default to v0

We can only bump the default once SBPFv3 is enabled on all three clusters (testnet, devnet, MNB), which we are still about 1.5 weeks short of.

**Comment by jalaziz** [comment]
> See discussion on Discord: https://discord.com/channels/428295358100013066/967028962746327060/1517048830145724486

I can't seem to comment in that channel, but the discussion clearly points to how broken this rollout process was.

Where are we supposed to test our program / upgrades? Is devnet not the official playground? If so, shouldn't the tooling reflect that? The changelog that was linked in the channel doesn't even warn about SIMD-0500.

We're in a situation now where we can't test the same binary on devnet and mainnet. I don't get how that is an acceptable choice for developers?

**Comment by Lichtso** [comment]
> Where are we supposed to test our program / upgrades?

https://docs.anza.xyz/cli/examples/test-validator

> Is devnet not the official playground

One of, but not the only one. We also want people to run an all features enabled test-validator so that they can get a longer time / earlier heads up on breaking changes.

> The changelog that was linked in the channel doesn't even warn about SIMD-0500.

There was a lot more than just a changelog entry. See tweets and even the Breakpoint talk linked on Discord.

> I don't get how that is an acceptable choice for developers

I understand that this is a troublesome situation, but "choice" is a bit strong. It was not designed that way. The release cadence was roughly doubled after the features were scheduled. These two events were meant to be 3 months apart.

**Comment by jalaziz** [comment]
> https://docs.anza.xyz/cli/examples/test-validator

The test validator is local only. That's great for local development and CI. It's not a great solution for a company testing solutions built on Solana.

> There was a lot more than just a changelog entry. See tweets and even the Breakpoint talk linked on Discord.

This ticket and the discussion in Discord would suggest that's not enough. I understand that the Solana team may think it was enough, but the community is clearly telling you it was not. It may have been enough if the tooling didn't break so badly and leave us in a situation where we are unable to test the same program binaries in both devnet and mainnet.

>  I understand that this is a troublesome situation, but "choice" is a bit strong. It was not designed that way. The release cadence was roughly doubled after the features were scheduled. These two events were meant to be 3 months apart.

Sure, but they weren't and instead us developers are left with broken tooling and broken deployments. The fact that we are unable to deploy the same program binary in mainnet and devnet today is a testing dealbreaker.

Also, the "release cadence forced this" argument is very troubling. That completely disregards the entire community that's building on Solana (who are effectively your "customers"). How are institutions supposed to trust Solana when the team makes decisions that don't prioritize testing, safety, and compatibility like this?

**Comment by Lichtso** [comment]
> when the team makes decisions

I am telling you there never was an explicit decision to get into this situation. It is an unintended consequence of other decisions. The release cadence change did not "force" this, but simply did not consider it at all.

> prioritize testing, safety, and compatibility

We absolutely do, I think you underestimate the complexity of these evolving systems. Furthermore, everything is still correct, in the sense that there are no bugs, it is a pure timing issue.

> I understand that the Solana team may think it was enough

So far I pointed you to announcements on: Twitter / X, Discord, dev meetups, Breakpoint talks, it is even shown on the Solana explorer:

<img width="1138" height="185" alt="Image" src="https://github.com/user-attachments/assets/4cb396b5-7c21-48fd-91d9-6e4a232caf6e" />

Yet, devs still manage to act suprised and caught off-guard by everything we do.

Anyway, trying to steer this discussion back on a constructive path: We are looking into the options to resolve this on Discord.

**Comment by archseer** [comment]
Well, even Anchor was caught by surprise: https://github.com/otter-sec/anchor/pull/4684

For what it's worth, just using `--arch v3` doesn't seem to work for me. I probably need to specify ` --tools-version v1.54` too? It would be nice if there was an official guidance somewhere in the docs, I only learned of the `--arch` flag after finding this github issue. (Yes we're on 3.1.14 since that's the version supported by the latest stable Anchor release.)

Edit: `solana-verify` doesn't even support `--tools-version` at all.

```
$ solana-verify build  --arch v3

Mounting path: /contracts
Workspace path: /contracts
Found docker image for Solana version 3.1.14
Workdir: /build
Building program at /build/
No Docker resource limits are set.
You can set the SVB_DOCKER_MEMORY_LIMIT and SVB_DOCKER_CPU_LIMIT environment variables to limit Docker resources.
For example: SVB_DOCKER_MEMORY_LIMIT=2g SVB_DOCKER_CPU_LIMIT=2.
Using container Rust toolchain: 1.86.0-x86_64-unknown-linux-gnu
   Compiling proc-macro2 v1.0.106
   Compiling unicode-ident v1.0.24
   Compiling quote v1.0.45
   Compiling serde_core v1.0.228
   Compiling hashbrown v0.17.0
   Compiling equivalent v1.0.2
   Compiling winnow v1.0.1
   Compiling toml_datetime v1.1.1+spec-1.1.0
   Compiling serde v1.0.228
   Compiling cfg_aliases v0.2.1
   Compiling once_cell v1.21.4
   Compiling five8_core v0.1.2
   Compiling version_check v0.9.5
   Compiling autocfg v1.5.0
error[E0463]: can't find crate for `core`
  |
  = note: the `sbpfv3-solana-solana` target may not be installed
  = help: consider adding the standard library to the sysroot with `x build library --target sbpfv3-solana-solana`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

**Comment by archseer** [comment]
Not working:

```
$ docker run --rm -it -v ${PWD}:/build solanafoundation/solana-verifiable-build:3.1.14 cargo build-sbf --tools-version v1.54 --arch v3
$ solana -V
solana-cli 4.0.2 (src:549805f3; feat:6ff76655, client:Agave)
$ solana program deploy -u devnet foo.so
Error: ELF error: ELF error: Failed to parse ELF file: invalid file header
```

I assume it's the `solana-loader-v3-interface`?

**Comment by ChewingGlass** [comment]
```
cargo-build-sbf --arch v3 --tools-version v1.54 --manifest-path programs/program/Cargo.toml
```

Worked for me. Just can't use anchor I guess? lol

**Comment by archseer** [comment]
Thanks for the pointer on `--manifest-path`, that worked. I was trying to build from the workspace root before. Looks like I need to compile these one by one.

**Comment by ChewingGlass** [comment]
My 2 cents here - yes enabling features (and the ordering of that across many clusters) is complicated. Yes these features are announced on various channels, far in advance, and devs should do a better job of watching for them.

But generally speaking, devs expect tooling to just work. When it doesn’t. They upgrade to see if that fixes it. In this case, upgrade doesn’t fix the issue because maintainers of tooling (like Anchor and Solana cli) never updated the defaults to Just Work™. Solana cli because of a timing issue, Anchor because I guess the maintainers didn’t see the announcements? 

You don’t need to reach out to every dev for an acknowledgment on new features. But there should certainly be an integration test on releasing new stuff: “does this break the most commonly used dev tooling” and if yes, proactively reach out to the maintainers. It’s crazy to me this could get released to devnet without someone reaching out to Anchor maintainers to get an “ack, this won’t break us”

**Comment by jalaziz** [comment]
My last comments on this subject:

1. The twitter announcements and change log made no indication that v0-v2 programs would start breaking. Only the explorer notice did. No announcement offered a solution or upgrade guide. Instead obscure flags are required to make programs work. Yet somehow we are all at fault for not paying enough attention.

2. As many others have mentioned. The most common dev tooling is broken. In fact, even with the obscure flag, one must use the latest toolchain for their programs to work. The developer tooling was not released with plenty of time for developers to naturally upgrade.

3. Yes these systems are complicated, but that's exactly why great care must be taken and why N+1/N+2 release schedules for breaking changes are standard. It really seems like no one bothered to consider the developer tooling based on the Discord discussions.

On the positive side, it seems like folks are taking this seriously on Discord and are admitting this was a serious blunder. Looks like there will be a reset tomorrow to fix this.

**Comment by acheroncrypto** [comment]
> Deployment of old programs have been disabled. You should now use `--arch v3` with a recent platform tools version. Note that `--arch v3` will still fail with an old version.

@LucasSte How recent? Surely not v1.53 (https://github.com/anza-xyz/platform-tools/pull/112) recent, right? Or are we literally disabling the deployment of all programs that don't use pretty much the latest versions of everything?

**Comment by jalaziz** [comment]
> > Deployment of old programs have been disabled. You should now use `--arch v3` with a recent platform tools version. Note that `--arch v3` will still fail with an old version.
> 
> @LucasSte How recent? Surely not v1.53 (https://github.com/anza-xyz/platform-tools/pull/112) recent, right? Or are we literally disabling the deployment of all programs that don't use pretty much the latest versions of everything?

I believe you must use v1.54.

**Comment by LucasSte** [comment]
> Thanks for the pointer on `--manifest-path`, that worked. I was trying to build from the workspace root before. Looks like I need to compile these one by one.

`cargo-build-sbf` has the `--workspace` argument, which allows you to build all crates in the workspace at once.

**Comment by LucasSte** [comment]
> > Deployment of old programs have been disabled. You should now use `--arch v3` with a recent platform tools version. Note that `--arch v3` will still fail with an old version.
> 
> [@LucasSte](https://github.com/LucasSte) How recent? Surely not v1.53 ([anza-xyz/platform-tools#112](https://github.com/anza-xyz/platform-tools/pull/112)) recent, right? Or are we literally disabling the deployment of all programs that don't use pretty much the latest versions of everything?

v1.53 is the earliest one you need to build with `--arch v3`. It was released in early February, so roughly four months ago. On one point, note that newer platform tool release can be used independently of your Solana CLI or `cargo-build-sbf` version with the argument `--tools-version`.

I recognized though that most people don't do that and simply default to the version hard coded on the `cargo-build-sbf` binary.

We began publishing `cargo-build-sbf` on `crates.io`, so that it can be installed and updated separately from solana CLI using `cargo install cargo-build-sbf`.

Now that I'm in the spotlight, I want to ask your opinion on these topics:

1. Should `cargo-build-sbf` always fetch the latest version of platform tools automatically instead of defaulting to a hard coded one? Should it instead warn that there is an update?
2. Should we unbundle `cargo-build-sbf` from Solana CLI? The consequence here is that the installation would need to be performed separately, however we might have some benefits, like better versioning (naming the releases the same as the Rust version), and a easier way to upgrade that is detached from the Agave or CLI version.

**Comment by LucasSte** [comment]
> Or are we literally disabling the deployment of all programs that don't use pretty much the latest versions of everything?

On this point, I recognize that there was too little time between enabling the new version and disabling the old ones. On the compiler tool side, the plan was to warn about deprecating once v3 was enabled on all clusters and then default the build to `--arch v3` on a following version, enabling a seamless transition. As discussed on discord, we opted for re-enabling v0 deployments on dev-net to space out the transition.

Now, can you all give our input on the questions I asked above?

**Comment by jalaziz** [comment]
> Should cargo-build-sbf always fetch the latest version of platform tools automatically instead of defaulting to a hard coded one? Should it instead warn that there is an update?

This would be nice if it's guaranteed not to result in compatibility issues (e.g. that the latest platform tools will always work with older versions of cargo-build-sbf). I think a better approach is to do something similar to rustup and other tools where a local file dictates the version of platform tools to use (e.g. `rust-toolchain.toml`). It might even be possible to put this within Cargo.toml using package or workspace metadata attributes.

>Should we unbundle cargo-build-sbf from Solana CLI? The consequence here is that the installation would need to be performed separately, however we might have some benefits, like better versioning (naming the releases the same as the Rust version), and a easier way to upgrade that is detached from the Agave or CLI version.

Isn't this already the case for some installation paths? At the very least, it's the case for homebrew installed Solana CLI. I would argue that unbundling makes it harder to get a working installation in a single step, but the pros likely outweigh the cons.

**Comment by acheroncrypto** [comment]
> On one point, note that newer platform tool release can be used independently of your Solana CLI or `cargo-build-sbf` version with the argument `--tools-version`.

Yes, I'm aware of this feature. However, with this approach, you are more or less hoping for the best and assuming there won't be any problems when trying to use an untested version (in terms of compatibility). There are *at least* 2 potential problematic scenarios:

1. Compile errors
2. Unexpected behavioral changes

To demonstrate, let's try this approach with an old program.

```sh
$ cargo-build-sbf --version
solana-cargo-build-sbf 1.17.34
platform-tools v1.37
rustc 1.68.0
```

Build with `--tools-version v1.54`:

```sh
$ cargo-build-sbf --tools-version v1.54
error[E0463]: can't find crate for `core`
  |
  = note: the `sbf-solana-solana` target may not be installed
  = help: consider adding the standard library to the sysroot with `x build library --target sbf-solana-solana`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

Looks like `cargo-build-sbf` might be incompatible, so let's try updating `cargo-build-sbf` to latest:

```sh
$ cargo-build-sbf --version
cargo-build-sbf 4.0.0
platform-tools v1.53
```

and re-run (with or without `--arch v3`):

```sh
$ cargo-build-sbf --tools-version v1.54 --arch v3
error[E0635]: unknown feature `stdsimd`
  --> src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
```

Cool, we ran into https://github.com/tkaitchuck/aHash/issues/200. Let's check the `ahash` version(s):

```sh
$ cargo tree -i ahash
error: specification `ahash` is ambiguous
help: re-run this command with one of the following specifications
  ahash@0.7.6
  ahash@0.8.3
```

Let's find a compatible version if it exists and update to those versions:

```sh
cargo update -p ahash@0.7.6 --precise 0.7.8
cargo update -p ahash@0.8.3 --precise 0.8.12
```

Re-try building:

```sh
$ cargo-build-sbf --tools-version v1.54 --arch v3
error: older versions of the `wasm-bindgen` crate are incompatible with current versions of Rust; please update to `wasm-bindgen` v0.2.88
```

Another compile error. I don't know what `wasm-bindgen` is doing here, but sure. Note that both of the compile errors came from indirect/transitive dependencies. Fixing such errors is usually more involved, since the problematic crate(s) might be getting used by multiple dependencies.

I'll stop debugging here because I think this is enough to get the point across.

Scenario 1 is annoying, but it's at least easily detectable. Scenario 2, on the other hand, can be very subtle. For example, during the Solana v1.17 -> v1.18 update (`platform-tools` v1.37 -> v1.39), stack usage of certain programs increased considerably, which sometimes led to *undetectable* UB (https://github.com/anza-xyz/agave/issues/252).

> I recognized though that most people don't do that and simply default to the version hard coded on the `cargo-build-sbf` binary.

Given the above reasoning, I'd personally avoid overriding the tools version as much as I can. It doesn't make sense to hope there won't be any compatibility issues.

> 1. Should `cargo-build-sbf` always fetch the latest version of platform tools automatically instead of defaulting to a hard coded one?

It should *never* automatically change the version imo, since it's not guaranteed to work.

> Should it instead warn that there is an update?

I wouldn't be against a warning about using an outdated version.

> 2\. Should we unbundle `cargo-build-sbf` from Solana CLI? The consequence here is that the installation would need to be performed separately, however we might have some benefits, like better versioning (naming the releases the same as the Rust version), and a easier way to upgrade that is detached from the Agave or CLI version.

Naming the releases the same as the Rust version would be great. However, I'd prefer to see all the differences between Solana's Rust and regular Rust be documented in detail before syncing the versions. Excuse my ignorance if such documentation already exists (not the one that bleakly mentions one can't use `std::fs` etc.).

Still, it also makes sense to append `solana` suffix to the Rust versions to emphasize the difference e.g. `1.96.0-solana`.

> On this point, I recognize that there was too little time between enabling the new version and disabling the old ones.

Why is the deployment of the old ones being disabled in the first place?

**Comment by MrSh4d0w18** [comment]
> > > Deployment of old programs have been disabled. You should now use `--arch v3` with a recent platform tools version. Note that `--arch v3` will still fail with an old version.
> > 
> > 
> > [@LucasSte](https://github.com/LucasSte) How recent? Surely not v1.53 ([anza-xyz/platform-tools#112](https://github.com/anza-xyz/platform-tools/pull/112)) recent, right? Or are we literally disabling the deployment of all programs that don't use pretty much the latest versions of everything?
> 
> v1.53 is the earliest one you need to build with `--arch v3`. It was released in early February, so roughly four months ago. On one point, note that newer platform tool release can be used independently of your Solana CLI or `cargo-build-sbf` version with the argument `--tools-version`.
> 
> I recognized though that most people don't do that and simply default to the version hard coded on the `cargo-build-sbf` binary.
> 
> We began publishing `cargo-build-sbf` on `crates.io`, so that it can be installed and updated separately from solana CLI using `cargo install cargo-build-sbf`.
> 
> Now that I'm in the spotlight, I want to ask your opinion on these topics:
> 
> 1. Should `cargo-build-sbf` always fetch the latest version of platform tools automatically instead of defaulting to a hard coded one? Should it instead warn that there is an update?
> 2. Should we unbundle `cargo-build-sbf` from Solana CLI? The consequence here is that the installation would need to be performed separately, however we might have some benefits, like better versioning (naming the releases the same as the Rust version), and a easier way to upgrade that is detached from the Agave or CLI version.

didnt expected so many attention on my topic, but in my humble opinion : 
1. Should cargo-build-sbf always fetch the latest platform tools?

No. absolutely not...builds should be reproducible and deterministic. Auto-updating compilers are quite dangerous because they can unexpectedly change binary output and break deployments, a warning about newer versions would be way better.

2. Should cargo-build-sbf be unbundled from Solana CLI?

Yes. compiler toolchain evolves independently from the CLI and runtime. Separating it would allow clearer versioning, easier upgrades/downgradeswhile keeping the Solana CLI focused on clusters interactiosn

**Comment by LucasSte** [comment]
> > On one point, note that newer platform tool release can be used independently of your Solana CLI or `cargo-build-sbf` version with the argument `--tools-version`.
> 
> Yes, I'm aware of this feature. However, with this approach, you are more or less hoping for the best and assuming there won't be any problems when trying to use an untested version (in terms of compatibility). There are _at least_ 2 potential problematic scenarios:
> 
> 1. Compile errors
> 2. Unexpected behavioral changes

I have heard the struggle of the update before, however, none of the problems you brought up are a consequence of our tooling customization. The Rust compiler changes and many of its constructs are not guaranteed to be stable. Bringing a newer version also brings in changes in the `core` and `std` library implementation that we don't really modify. These changes sometimes impact the performance of programs and usability of APIs.

In part, we are to blame because we don't bring Rust updates so often. We usually jump five versions each update, and that always carries lots of changes with it. 

Our mitigation plan was to phase out the STD library from Rust, as soon as Anchor is ready to move away from it. That way, we can increase the cadence of our releases, since updates will be less burdensome. Moving away from STD also opens up for other toolchains, like the one Blueshift is developing for Solana or using GCC, whose community is adding support for Solana ([source](https://lwn.net/SubscriberLink/1071973/b1fdf813813a59ec/). My bet is that more frequent updates would soften the burden, right?

I believe, though, that developers should have quicker access to these updates, hence the idea to unbundle `cargo-build-sbf` and ship it separately. Apart from architecture changes, which we have none planned besides the ones discussed here, the compiler version is independent of the CLI or cluster version and should work together.

> Scenario 2, on the other hand, can be very subtle. For example, during the Solana v1.17 -> v1.18 update (`platform-tools` v1.37 -> v1.39), stack usage of certain programs increased considerably, which sometimes led to _undetectable_ UB ([#252](https://github.com/anza-xyz/agave/issues/252)).

I remember this scenario. A bug in code generation lead to the behavior being undetected. We investigated and added a warning when that was happening. The increase in stack usage, though, was related to Rust's internal changes, on which we have no control on.

> Naming the releases the same as the Rust version would be great. However, I'd prefer to see all the differences between Solana's Rust and regular Rust be documented in detail before syncing the versions. Excuse my ignorance if such documentation already exists (not the one that bleakly mentions one can't use `std::fs` etc.).

Thanks for noting. We can create a document mentioning the differences. 

> Still, it also makes sense to append `solana` suffix to the Rust versions to emphasize the difference e.g. `1.96.0-solana`.

Since https://github.com/anza-xyz/agave/pull/6981, the rust toolchain has been renamed to the format `<rust_version>-sbpf-solana-<platform_tools_version>`, like in `1.89.0-sbpf-solana-v1.53`. 

Maybe I should announce these changes clearer. Perhaps I should post something on our `platform-tools` channel or Discord? O post on Anchor's discord server?

> > On this point, I recognize that there was too little time between enabling the new version and disabling the old ones.
> 
> Why is the deployment of the old ones being disabled in the first place?

I'll list the reasons here, but basically the third one was the deciding factor to disable.

1. Old versions have a bug in constant data: https://github.com/anza-xyz/platform-tools/issues/114. We can only fix those with a difference relocation scheme and a new version. The fix cannot be on the compiler only and needs a validator patch. Since it becomes incompatible with old programs, it needs a new version.
2. Old versions include dynamic relocations and have a performance impact on the cluster.
3. All the old versions have security problems. Although there are mitigations in place, blocking new deployments guarantees the safety of the network. It is the best interest of the Solana community that we maintain the network safe and deprecate old programs.

PS: Existing programs will continue to work. You won't be able to deploy new ones with the deprecated versions.

**Comment by LucasSte** [comment]
> > Should cargo-build-sbf always fetch the latest version of platform tools automatically instead of defaulting to a hard coded one? Should it instead warn that there is an update?
> 
> This would be nice if it's guaranteed not to result in compatibility issues (e.g. that the latest platform tools will always work with older versions of cargo-build-sbf). I think a better approach is to do something similar to rustup and other tools where a local file dictates the version of platform tools to use (e.g. `rust-toolchain.toml`). It might even be possible to put this within Cargo.toml using package or workspace metadata attributes.

Since https://github.com/anza-xyz/agave/pull/2914, it is possible to specify the tools version on the `Cargo.toml`, but maybe it is not as useful as we had thought.

**Comment by jalaziz** [comment]
> Since https://github.com/anza-xyz/agave/pull/2914, it is possible to specify the tools version on the Cargo.toml, but maybe it is not as useful as we had thought.

Ah, did not know that. It doesn't really come up in searches and haven't found references to it in documentation.

I just tested it and it works great. Although, anchor still barfs on IDL issue when `--arch v3` is passed, but that's a separate issue.

That being said, I'm a huge fan of codifying everything instead of relying on command-line flags., so it would be great if `arch` could also be codified in `Cargo.toml` (or, hopefully, Anchor exposes it in Anchor.toml).

Separately, while `platform-tools` can be pinned in `Cargo.toml` is there a good way to pin `cargo-build-sbf`? Or does that not actually matter?

Outside of installing it as part of the Solana CLI, it seems the next best option is `cargo install` which doesn't have a declarative file-based approach for managing versions. Yes, we could use `mise` and/or `nix` to help, but I'm curious how the Solana team is thinking about it.

**Comment by LucasSte** [comment]
> That being said, I'm a huge fan of codifying everything instead of relying on command-line flags., so it would be great if `arch` could also be codified in `Cargo.toml` (or, hopefully, Anchor exposes it in Anchor.toml).

I know this is convenient, but at the same time, we will make v3 as the default version to build with in two cargo-build-sbf versions away. The next version will include a warning telling people to migrate. Since the old versions are going away, I believe it is best to default to the newest one.

> Separately, while `platform-tools` can be pinned in `Cargo.toml` is there a good way to pin `cargo-build-sbf`? Or does that not actually matter?

Apart from minor fixes, and bumping the default platform tools version, there aren't that many changes between cargo-build-sbf releases.

 
I forgot to mention earlier, but, for those following the thread, using v3 (together with platform tools version v1.54) brings some benefits to developers:

1. Program will use less CUs: checking [anchor's own benchmark](https://github.com/otter-sec/anchor/pull/4684/changes#diff-640e0634b746fc2875e2291cb9d45cd500925453a70ff28cd0d08748c35c322b), you have gains of up to 28%!
2. Programs will be smaller, so you'll use less SOL for deployment. Checking [anchor's benchmark again](https://github.com/otter-sec/anchor/pull/4684/changes#diff-b712e855302beef466bedeb086f9fa2d0cc19bef95b70931105cb891214acf9b), the program is 11% smaller.

**Comment by steviez** [comment]
SIMD-0500 has been deactivated on devnet
```
$ solana feature status -ud | grep 0500
B8JJXCy5amZyWG9r7EnUYLwzXSXTxG7GZ1qZ1qggo83g | inactive                | NA              | SIMD-0500: Disable deployment of SBPF v0, v1 and v2 programs
```
and remains deactivated on MNB
```
$ solana feature status -um | grep 0500
B8JJXCy5amZyWG9r7EnUYLwzXSXTxG7GZ1qZ1qggo83g | inactive                | NA              | SIMD-0500: Disable deployment of SBPF v0, v1 and v2 programs
```
so I think we can close this issue out for now. I believe further discussion/comms/etc will take place elsewhere for getting SIMD-0500 back into the feature activation queue
